# Generated by Django 4.1 on 2022-08-03 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_zipfile_generatedfavicon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generatedfavicon',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='generatedfavicon',
            old_name='zip_file_id',
            new_name='zip_file',
        ),
        migrations.RenameField(
            model_name='zipfile',
            old_name='user_id',
            new_name='user',
        ),
    ]
