# Generated by Django 4.1 on 2022-08-03 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_user_id_generatedfavicon_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedfavicon',
            name='path',
            field=models.FileField(upload_to='medias'),
        ),
        migrations.AlterField(
            model_name='zipfile',
            name='path',
            field=models.FileField(upload_to='medias'),
        ),
    ]
