# Generated by Django 4.1 on 2022-08-03 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_generatedfavicon_path_alter_zipfile_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedfavicon',
            name='path',
            field=models.FileField(blank=True, null=True, upload_to='generator/'),
        ),
        migrations.AlterField(
            model_name='zipfile',
            name='path',
            field=models.FileField(blank=True, null=True, upload_to='generator/'),
        ),
    ]
