# Generated by Django 4.1 on 2022-08-07 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_uploadedfile_convertedfavicon'),
    ]

    operations = [
        migrations.AddField(
            model_name='convertedfavicon',
            name='saved_to_drafts',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='convertedfavicon',
            name='size',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='faviconzipfile',
            name='saved_to_drafts',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='generatedfavicon',
            name='saved_to_drafts',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='generatedfavicon',
            name='size',
            field=models.IntegerField(null=True),
        ),
    ]
