# Generated by Django 4.1 on 2022-08-12 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_texticons_usertexticon'),
    ]

    operations = [
        migrations.AddField(
            model_name='texticons',
            name='html_code',
            field=models.CharField(default='', max_length=255),
        ),
    ]
